//! World-level placement: where each zone's local origin sits in
//! world-meter coordinates, plus the island-scale features (coastline,
//! mountain ranges, cross-zone scars) that don't belong to any single
//! zone. Loaded from `src/generated/world/world.yaml`.
//!
//! This file is the single source of truth for zone placement. The
//! constants previously hardcoded in `vaern-client::voxel_biomes::ZONE_RING_RADIUS`,
//! `vaern-client::scene::dressing`, and `vaern-server::data` are
//! superseded by `WorldLayout::zone_origin()`.

use std::{collections::HashMap, fs, path::Path};

use serde::{Deserialize, Serialize};

use crate::{Coord2, LoadError, PolyPath, Polygon};

/// One zone's placement in world-meter coordinates.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ZonePlacement {
    pub zone: String,
    /// Where this zone's local `(0, 0)` sits in world meters.
    pub world_origin: Coord2,
    /// If the zone's local axes are rotated relative to the world's
    /// (e.g. the kingsroad runs north-east instead of due east),
    /// declare it here. Default 0 = no rotation.
    #[serde(default)]
    pub rotation_deg: f32,
    /// Painting order for the world atlas. Higher z-index draws on
    /// top of lower.
    #[serde(default = "default_z_index")]
    pub z_index: i32,
    /// Voronoi cell of this zone clipped to the world coastline,
    /// in world-meter coords. Generated by
    /// `scripts/balance_world_layout.py`. None for zones not yet
    /// placed in `world.yaml`.
    #[serde(default)]
    pub zone_cell: Option<crate::Polygon>,
}

fn default_z_index() -> i32 {
    1
}

/// One island-scale feature: ocean polygon, mountain spine, etc.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum WorldFeature {
    Ocean {
        id: String,
        polygon: Polygon,
        #[serde(default)]
        label_position: Option<Coord2>,
    },
    MountainRange {
        id: String,
        spine_path: PolyPath,
        /// Width of the painted band, in world meters.
        #[serde(default = "default_mountain_width")]
        width: f32,
        #[serde(default)]
        label_position: Option<Coord2>,
    },
    Scar {
        id: String,
        polygon: Polygon,
        #[serde(default)]
        label_position: Option<Coord2>,
    },
}

fn default_mountain_width() -> f32 {
    800.0
}

/// World-level layout document.
#[derive(Debug, Clone, Default, Deserialize, Serialize)]
pub struct WorldLayout {
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub schema_version: String,
    #[serde(default)]
    pub zone_placements: Vec<ZonePlacement>,
    #[serde(default)]
    pub coastline: Option<Polygon>,
    #[serde(default)]
    pub world_features: Vec<WorldFeature>,
}

impl WorldLayout {
    /// World-meter origin for the named zone, if it's placed.
    pub fn zone_origin(&self, zone_id: &str) -> Option<Coord2> {
        self.zone_placements
            .iter()
            .find(|p| p.zone == zone_id)
            .map(|p| p.world_origin)
    }

    /// All placements as a `zone_id → ZonePlacement` map.
    pub fn placements_by_id(&self) -> HashMap<&str, &ZonePlacement> {
        self.zone_placements
            .iter()
            .map(|p| (p.zone.as_str(), p))
            .collect()
    }
}

/// Load `world.yaml` from the world root. Returns an empty layout if
/// the file doesn't exist (so the workspace still builds before the
/// migration script runs).
pub fn load_world_layout(world_root: impl AsRef<Path>) -> Result<WorldLayout, LoadError> {
    let path = world_root.as_ref().join("world.yaml");
    if !path.exists() {
        return Ok(WorldLayout::default());
    }
    let text = fs::read_to_string(&path).map_err(|e| LoadError::Io {
        path: path.clone(),
        source: e,
    })?;
    let layout: WorldLayout = serde_yaml::from_str(&text).map_err(|e| LoadError::Yaml {
        path: path.clone(),
        source: e,
    })?;
    Ok(layout)
}
