//! Analytic SDF primitives — closed-form distance functions used as
//! brush shapes and generator building blocks.
//!
//! Each primitive stores its world-space parameters directly; the SDF
//! evaluation is a single arithmetic expression (no chunk lookups), so
//! primitives are cheap to clone and pass into composite SDFs by value.

use super::SdfField;
use bevy::math::{Vec2, Vec3};

/// Solid sphere.
#[derive(Clone, Copy, Debug)]
pub struct Sphere {
    pub center: Vec3,
    pub radius: f32,
}

impl Sphere {
    pub const fn new(center: Vec3, radius: f32) -> Self {
        Self { center, radius }
    }
}

impl SdfField for Sphere {
    #[inline]
    fn sample(&self, p: Vec3) -> f32 {
        (p - self.center).length() - self.radius
    }
}

/// Axis-aligned solid box (not rotated — for rotated boxes, transform
/// the query point into the box's local frame before sampling).
#[derive(Clone, Copy, Debug)]
pub struct BoxSdf {
    pub center: Vec3,
    pub half_extents: Vec3,
}

impl BoxSdf {
    pub const fn new(center: Vec3, half_extents: Vec3) -> Self {
        Self { center, half_extents }
    }
}

impl SdfField for BoxSdf {
    #[inline]
    fn sample(&self, p: Vec3) -> f32 {
        // Inigo Quilez's standard box SDF.
        let d = (p - self.center).abs() - self.half_extents;
        let outside = d.max(Vec3::ZERO).length();
        let inside = d.x.max(d.y.max(d.z)).min(0.0);
        outside + inside
    }
}

/// Y-axis solid cylinder with flat caps. For arbitrary axes, transform
/// the query point into the cylinder's local frame before sampling.
#[derive(Clone, Copy, Debug)]
pub struct Cylinder {
    pub center: Vec3,
    pub radius: f32,
    pub half_height: f32,
}

impl Cylinder {
    pub const fn new(center: Vec3, radius: f32, half_height: f32) -> Self {
        Self {
            center,
            radius,
            half_height,
        }
    }
}

impl SdfField for Cylinder {
    #[inline]
    fn sample(&self, p: Vec3) -> f32 {
        // Inigo Quilez's standard cylinder SDF: 2D distance in the
        // (xz_radius, |local_y|) plane with rectangular cap.
        let local = p - self.center;
        let xz = Vec2::new(local.x, local.z).length();
        let d = Vec2::new(xz - self.radius, local.y.abs() - self.half_height);
        let outside = d.max(Vec2::ZERO).length();
        let inside = d.x.max(d.y).min(0.0);
        outside + inside
    }
}

/// Line segment swept into a solid cylinder with hemispherical caps.
/// Good for trenches, swept-brush strokes, and attack-path carving.
#[derive(Clone, Copy, Debug)]
pub struct Capsule {
    pub a: Vec3,
    pub b: Vec3,
    pub radius: f32,
}

impl Capsule {
    pub const fn new(a: Vec3, b: Vec3, radius: f32) -> Self {
        Self { a, b, radius }
    }
}

impl SdfField for Capsule {
    #[inline]
    fn sample(&self, p: Vec3) -> f32 {
        let pa = p - self.a;
        let ba = self.b - self.a;
        let denom = ba.dot(ba);
        // Degenerate capsule (a == b) → falls back to a sphere at a.
        let h = if denom > 1e-6 {
            (pa.dot(ba) / denom).clamp(0.0, 1.0)
        } else {
            0.0
        };
        (pa - ba * h).length() - self.radius
    }
}

/// Infinite horizontal plane at `y`. Solid below, air above. The
/// workhorse "ground" primitive — compose with noise to get natural
/// terrain.
#[derive(Clone, Copy, Debug)]
pub struct Plane {
    pub y: f32,
}

impl Plane {
    pub const fn horizontal(y: f32) -> Self {
        Self { y }
    }
}

impl SdfField for Plane {
    #[inline]
    fn sample(&self, p: Vec3) -> f32 {
        // Positive above the plane (air), negative below (solid).
        // Matches the crate-wide convention: `+ = air, − = solid`.
        p.y - self.y
    }
}

/// SDF generated by extruding an arbitrary f32 heightfield `h(x, z)`
/// into a solid volume. Every point below the height surface is solid,
/// every point above is air. Distance is approximated as the vertical
/// gap — exact for near-horizontal surfaces, slightly overestimates
/// near cliffs. Good enough for meshing purposes.
pub struct HeightfieldSdf<F: Fn(f32, f32) -> f32 + Send + Sync> {
    height_fn: F,
}

impl<F: Fn(f32, f32) -> f32 + Send + Sync> HeightfieldSdf<F> {
    pub fn new(height_fn: F) -> Self {
        Self { height_fn }
    }
}

impl<F: Fn(f32, f32) -> f32 + Send + Sync> SdfField for HeightfieldSdf<F> {
    #[inline]
    fn sample(&self, p: Vec3) -> f32 {
        let h = (self.height_fn)(p.x, p.z);
        // Positive above ground (air), negative below.
        p.y - h
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn box_is_zero_on_face() {
        let b = BoxSdf::new(Vec3::ZERO, Vec3::splat(2.0));
        assert!(b.sample(Vec3::new(2.0, 0.0, 0.0)).abs() < 1e-4);
    }

    #[test]
    fn cylinder_sdf_zero_on_side_surface() {
        let c = Cylinder::new(Vec3::ZERO, 5.0, 10.0);
        // Side surface at xz_radius == radius, |y| < half_height.
        assert!(c.sample(Vec3::new(5.0, 0.0, 0.0)).abs() < 1e-4);
    }

    #[test]
    fn cylinder_sdf_zero_on_top_cap() {
        let c = Cylinder::new(Vec3::ZERO, 5.0, 10.0);
        // Top cap at xz < radius, y == half_height.
        assert!(c.sample(Vec3::new(0.0, 10.0, 0.0)).abs() < 1e-4);
    }

    #[test]
    fn capsule_degenerate_is_sphere() {
        let c = Capsule::new(Vec3::ZERO, Vec3::ZERO, 3.0);
        assert!(c.sample(Vec3::new(3.0, 0.0, 0.0)).abs() < 1e-4);
    }

    #[test]
    fn plane_flips_sign_on_crossing() {
        let pl = Plane::horizontal(0.0);
        assert!(pl.sample(Vec3::new(0.0, 1.0, 0.0)) > 0.0);
        assert!(pl.sample(Vec3::new(0.0, -1.0, 0.0)) < 0.0);
    }

    #[test]
    fn heightfield_follows_curve() {
        let f = HeightfieldSdf::new(|x, _z| (x * 0.1).sin() * 2.0);
        // Above the sine wave → air.
        assert!(f.sample(Vec3::new(0.0, 10.0, 0.0)) > 0.0);
        assert!(f.sample(Vec3::new(0.0, -10.0, 0.0)) < 0.0);
    }
}
